#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

build()
{
    base=$1
    machine=$2
    branch=$3

    tag="${machine}-$(echo "${branch}" \
            | sed -e 's/^BSP-//' -e 's/-update/u/' -e 's/\.//g' -e 's/-RT/rt/')"

    docker build \
        --build-arg builder_base="anyakichi/yocto-builder:${base:-latest}" \
        --build-arg meta_rzg2_branch="${branch}" \
        --build-arg yocto_machine="${machine}" \
        -t "${DOCKER_REPO}:${tag}" \
        .
}

if [ $# -eq 0 ]; then
    for v in BSP-1.0.0 BSP-1.0.1{,-update1} BSP-1.0.2{,-update1} \
            BSP-1.0.3{,-RT} BSP-1.0.4{,-RT}{,-update1} \
            BSP-1.0.5{,-RT{,-update1}} BSP-1.0.6{,-RT,-update1}; do
        build xenial-rocko ek874 "$v"
        if [[ ! "$v" < BSP-1.0.1 ]]; then
            build xenial-rocko hihope-rzg2m "$v"
        fi
        if [[ ! "$v" < BSP-1.0.2 ]]; then
            build xenial-rocko hihope-rzg2n "$v"
        fi
        if [[ ! "$v" < BSP-1.0.4 ]]; then
            build xenial-rocko hihope-rzg2h "$v"
        fi
    done
else
    build "$@"
fi
