#!/bin/bash

push()
{
    machine=$1
    branch=$2

    tag="${machine}-$(echo "${branch}" \
            | sed -e 's/^BSP-//' -e 's/-update/u/' -e 's/\.//g' -e 's/-RT/rt/')"

    docker push "${DOCKER_REPO}:${tag}"
}

docker push "${DOCKER_REPO}:template"

for v in BSP-1.0.0 BSP-1.0.1{,-update1} BSP-1.0.2{,-update1} \
        BSP-1.0.3{,-RT} BSP-1.0.4{,-RT}{,-update1} \
        BSP-1.0.5{,-RT{,-update1}} BSP-1.0.6{,-RT,-update1} \
        BSP-1.0.7{,-RT} BSP-1.0.8; do
    push ek874 "$v"
    if [[ ! "$v" < BSP-1.0.1 ]]; then
        push hihope-rzg2m "$v"
    fi
    if [[ ! "$v" < BSP-1.0.2 ]]; then
        push hihope-rzg2n "$v"
    fi
    if [[ ! "$v" < BSP-1.0.4 ]]; then
        push hihope-rzg2h "$v"
    fi
done
