name: Publish Docker image
on:
  push:
  workflow_dispatch:
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base_machine_rev:
          [
            [focal-dunfell, ek874, BSP-3.0.0],
            [focal-dunfell, hihope-rzg2h, BSP-3.0.0],
            [focal-dunfell, hihope-rzg2m, BSP-3.0.0],
            [focal-dunfell, hihope-rzg2n, BSP-3.0.0],
            [focal-dunfell, smarc-rzg2l, BSP-3.0.0],
            [focal-dunfell, smarc-rzg2lc, BSP-3.0.0],
            [focal-dunfell, smarc-rzg2ul, BSP-3.0.0],
            [focal-dunfell, ek874, BSP-3.0.1],
            [focal-dunfell, hihope-rzg2h, BSP-3.0.1],
            [focal-dunfell, hihope-rzg2m, BSP-3.0.1],
            [focal-dunfell, hihope-rzg2n, BSP-3.0.1],
            [focal-dunfell, smarc-rzg2l, BSP-3.0.1],
            [focal-dunfell, smarc-rzg2lc, BSP-3.0.1],
            [focal-dunfell, smarc-rzg2ul, BSP-3.0.1],
            [focal-dunfell, ek874, BSP-3.0.5-update3],
            [focal-dunfell, hihope-rzg2h, BSP-3.0.5-update3],
            [focal-dunfell, hihope-rzg2m, BSP-3.0.5-update3],
            [focal-dunfell, hihope-rzg2n, BSP-3.0.5-update3],
            [focal-dunfell, smarc-rzg2l, BSP-3.0.5-update3],
            [focal-dunfell, smarc-rzg2lc, BSP-3.0.5-update3],
            [focal-dunfell, smarc-rzg2ul, BSP-3.0.5-update],
            [focal-dunfell, ek874, BSP-3.0.6],
            [focal-dunfell, hihope-rzg2h, BSP-3.0.6],
            [focal-dunfell, hihope-rzg2m, BSP-3.0.6],
            [focal-dunfell, hihope-rzg2n, BSP-3.0.6],
            [focal-dunfell, smarc-rzg2l, BSP-3.0.6],
            [focal-dunfell, smarc-rzg2lc, BSP-3.0.6],
            [focal-dunfell, smarc-rzg2ul, BSP-3.0.6],
            [focal-dunfell, ek874, BSP-3.0.6-update4],
            [focal-dunfell, hihope-rzg2h, BSP-3.0.6-update4],
            [focal-dunfell, hihope-rzg2m, BSP-3.0.6-update4],
            [focal-dunfell, hihope-rzg2n, BSP-3.0.6-update4],
            [focal-dunfell, smarc-rzg2l, BSP-3.0.6-update4],
            [focal-dunfell, smarc-rzg2lc, BSP-3.0.6-update4],
            [focal-dunfell, smarc-rzg2ul, BSP-3.0.6-update4],
            [jammy-dunfell, ek874, BSP-3.0.7],
            [jammy-dunfell, hihope-rzg2h, BSP-3.0.7],
            [jammy-dunfell, hihope-rzg2m, BSP-3.0.7],
            [jammy-dunfell, hihope-rzg2n, BSP-3.0.7],
            [jammy-dunfell, smarc-rzg2l, BSP-3.0.7],
            [jammy-dunfell, smarc-rzg2lc, BSP-3.0.7],
            [jammy-dunfell, smarc-rzg2ul, BSP-3.0.7],
            [jammy-dunfell, smarc-rzv2l, BSP-3.0.7],
          ]
    steps:
      - run: |
          if [[ ${{ github.ref }} == "refs/heads/main" ]]; then
            prefix=
          else
            prefix="$(echo ${{ github.ref }} | sed -e 's,.*/,,')-"
          fi
          version=$(echo "${{ matrix.base_machine_rev[2] }}" | sed -r -e 's/^(BSP-|rzg2l_bsp_v)//' -e 's/-update/u/' -e 's/\.//g' -e 's/-RT/rt/')
          echo TAGS="${prefix}${{ matrix.base_machine_rev[1] }}-${version}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            anyakichi/yocto-rzg2-builder
            ghcr.io/anyakichi/yocto-rzg2-builder
          tags: ${{ env.TAGS }}
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            base=${{ matrix.base_machine_rev[0] }}
            meta_renesas_rev=${{ matrix.base_machine_rev[2] }}
            yocto_machine=${{ matrix.base_machine_rev[1] }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
