name: Publish Docker image
on:
  push:
  workflow_dispatch:
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        machine:
          - ek874
          - hihope-rzg2h
          - hihope-rzg2m
          - hihope-rzg2n
          - smarc-rzg2l
          - smarc-rzg2lc
          - smarc-rzg2ul
          - smarc-rzv2l
    steps:
      - run: |
          version=$(echo "${{ github.ref_name }}" | sed -r -e 's/^(BSP-|rzg2l_bsp_v)//' -e 's/-update/u/' -e 's/\.//g' -e 's/-RT/rt/')
          echo TAGS="${{ matrix.machine }}-${version}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            anyakichi/yocto-rzg2-builder
            ghcr.io/anyakichi/yocto-rzg2-builder
          tags: ${{ env.TAGS }}
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            yocto_machine=${{ matrix.machine }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
